server:
  port: 7001

spring:
  application:
    name: eureka-server7001

eureka:
  instance:
    hostname: eurekaserver7001.com # Eureka服务器实例名
  client:
    fetch-registry: false  # 是否获取服务注册表
    register-with-eureka: false # 是否注册到Eureka服务器
    service-url:
      defaultZone: http://eurekaserver7002.com:7002/eureka/ # 服务注册中心的URL