server:
  port: 8080

spring:
  application:
    name: consumer-order-service
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.mjh.springcloud.po

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: consumer-order-service
    prefer-ip-address: true # 访问路径显示ip地址

ribbon:
  # 建立连接的最大时间
  ConnectTimeout: 5000
  # 建立连接后读取数据的最大时间
  ReadTimeout: 5000