server:
  port: 8080

spring:
  application:
    name: consumer-order-service
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.mjh.springcloud.po

# eureka config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: consumer-order-service
    # show ip address
    prefer-ip-address: true

# ribbon config
ribbon:
  # connection creation timeout
  ConnectTimeout: 10000
  # read data timeout after creating connection
  ReadTimeout: 10000

# feign config
feign:
  circuitbreaker:
    enabled: true

# hystrix config
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000